name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: tracker_user
          POSTGRES_PASSWORD: cdfgxdcgcdfg
          POSTGRES_DB: trackerdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Generate Prisma client
        working-directory: backend
        run: npx prisma generate

      - name: Run backend tests
        working-directory: backend
        run: npm run test || echo "No backend tests yet"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend lint
        working-directory: frontend
        run: npm run lint || echo "No lint script yet"

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test -- --watch=false || echo "No frontend tests yet"

      - name: Build frontend
        working-directory: frontend
        run: npm run build -- --configuration=production
